In [1]:
import gpu_tracking
df = gpu_tracking.batch(
    r'/Users/amfaber/Documents/tracking_script/gpu-tracking/testing/easy_test_data.tif',
    9,
    filter_close = True,
    characterize = True,
    doughnut_correction = True,
    snr = 1.5,
    minmass_snr = 0.3,
    truncate_preprocessed = True,
    search_range = 13
)

In [12]:
%%timeit
df.groupby("particle")["frame"].apply(lambda x: x.iloc[-1] - x.iloc[0])

554 ms ± 1.71 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [9]:

next(iter(df.groupby("particle")))[1]

,frame,y,x,mass,Rg,raw,signal,ecc,particle,raw_mass,raw_bg_median,raw_mass_corrected
0,0,300.835693,19.909794,837.707092,1.679591,105138.0,99.645973,NaN,0,147653.0,2110.0,2063.0
28,1,300.668732,20.274799,895.609863,1.907034,105230.0,87.046127,NaN,0,147803.0,2105.0,2558.0

In [13]:
gpu_tracking.characterize_points(
    r'/Users/amfaber/Documents/tracking_script/gpu-tracking/testing/easy_test_data.tif',
    df,
    9,
    filter_close = True,
    characterize = True,
    doughnut_correction = True,
    snr = 0,
    minmass_snr = 0.3,
    truncate_preprocessed = True,
)

,frame,y,x,mass,Rg,raw,signal,ecc,raw_mass,raw_bg_median,raw_mass_corrected
0,0,413.065247,502.980103,1346.004639,1.635221,105696.0,148.588654,NaN,147771.0,2088.0,3699.0
1,0,111.672752,333.889984,2523.538574,1.676097,108940.0,258.473419,NaN,151559.0,2113.0,5762.0
2,0,454.033142,360.019714,800.005371,1.806427,104637.0,85.453979,NaN,147079.0,2105.0,1834.0
3,0,390.241364,220.055573,890.364929,1.791560,104342.0,86.039795,NaN,146567.0,2095.0,2012.0
4,0,219.481674,280.281616,1579.095215,1.964314,107415.0,138.752411,NaN,149939.0,2106.0,4625.0
...,...,...,...,...,...,...,...,...,...,...,...
251455,4999,182.327896,372.077423,2685.176025,1.712738,110298.0,233.810562,NaN,152922.0,2112.0,7194.0
251456,4999,81.985001,400.797729,1206.162354,2.199495,106472.0,75.241310,NaN,148833.0,2106.0,3519.0
251457,4999,114.145241,235.099091,938.776062,2.021075,104882.0,80.681259,NaN,146865.0,2102.0,1827.0
251458,4999,212.951523,217.151917,939.191040,1.536493,105319.0,120.455551,NaN,147868.0,2107.0,2485.0
251459,4999,19.599836,259.049072,1050.218262,1.751278,105143.0,112.735466,NaN,147083.0,2090.0,2873.0