In [7]:
import gpu_tracking
df = gpu_tracking.LoG(
    r'C:\Users\andre\Downloads\1&7 A647.tif - drift corrected.tif',
    2.2,
    3.5,
    n_radii = 10,
    log_spacing = False,
    overlap_threshold = 0,
    characterize = True,
    doughnut_correction = True,
    snr = 1.5,
    minmass_snr = 0.3,
    truncate_preprocessed = True,
    illumination_sigma = 30,
    illumination_correction_per_frame = True,
)

In [8]:
df

,frame,y,x,mass,r,Rg,raw,signal,ecc,raw_mass,raw_bg_median,raw_mass_corrected
0,0,347.882355,157.966110,7.450077,3.5,1.539009,52.943432,0.789496,0.089640,561555.0,11080.0,151595.0
1,0,419.894958,269.808350,6.132374,3.5,1.633082,52.241138,0.587142,0.084197,528708.0,10824.0,128220.0
2,0,503.123566,355.140533,5.789079,3.5,1.483075,47.640480,0.667193,0.054001,430824.0,8987.0,98305.0
3,0,170.391983,5.365817,5.212142,3.5,1.572888,46.931431,0.560668,0.125281,467349.0,9995.0,97534.0
4,0,273.815613,204.937531,5.183630,3.5,1.514907,48.160839,0.592929,0.121734,538576.0,11621.0,108599.0
...,...,...,...,...,...,...,...,...,...,...,...,...
31512,380,168.943466,498.729156,2.801194,2.2,1.383101,13.187100,0.313723,0.349108,149198.0,11905.0,-5567.0
31513,380,237.983704,498.647736,2.796274,2.2,1.398138,13.353673,0.307765,0.325050,132463.0,10998.0,-10511.0
31514,380,217.049973,498.679321,2.779898,2.2,1.385909,13.479635,0.312038,0.318053,134279.0,11294.0,-12543.0
31515,380,266.994080,498.672974,2.721688,2.2,1.393892,13.031152,0.292956,0.319061,131277.0,10616.0,-6731.0
31516,380,227.939835,271.764191,2.534245,2.2,1.322165,20.769730,0.300943,0.152644,332187.0,20560.0,64907.0

In [ ]:
import trackpy

In [5]:
df

,frame,y,x,mass,Rg,raw,signal,ecc,raw_mass,raw_bg_median,raw_mass_corrected,particle,duration
0,0,242.034973,45.833038,1014.742615,1.584365,105232.0,124.450340,0.217858,148073.0,2108.0,2621.0,0,2
1,0,386.571167,92.258514,929.550842,1.922515,104484.0,84.920723,0.254851,146190.0,2102.0,1152.0,1,1
2,0,167.208405,101.530876,1336.201660,1.910886,106341.0,117.441513,0.311408,149366.0,2107.0,3983.0,2,10
3,0,300.835693,19.909800,837.696716,1.679582,105138.0,99.645515,0.074096,147653.0,2110.0,2063.0,3,2
4,0,331.987976,47.491703,1157.145264,2.055535,106083.0,106.742615,0.360282,148203.0,2105.0,2958.0,4,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...
199012,4999,335.672913,209.956894,3188.677490,1.973878,111048.0,224.850922,0.253611,153749.0,2114.0,7883.0,27431,1670
199013,4999,394.831818,259.950256,2766.989746,2.094994,110451.0,217.935364,0.349202,154939.0,2110.0,9349.0,43455,24
199014,4999,373.865845,327.417358,4217.104492,1.608756,113261.0,414.960144,0.094529,156606.0,2108.0,11154.0,43459,23
199015,4999,182.862930,323.427124,2752.884766,1.625927,110197.0,290.504883,0.090787,153284.0,2117.0,7211.0,42666,105
199016,4999,216.849014,314.079224,1946.677856,1.836196,108602.0,150.619553,0.205580,151585.0,2114.0,5719.0,43476,22

In [12]:
%%timeit
df.groupby("particle")["frame"].apply(lambda x: x.iloc[-1] - x.iloc[0])

554 ms Â± 1.71 ms per loop (mean Â± std. dev. of 7 runs, 1 loop each)

In [9]:

next(iter(df.groupby("particle")))[1]

,frame,y,x,mass,Rg,raw,signal,ecc,particle,raw_mass,raw_bg_median,raw_mass_corrected
0,0,300.835693,19.909794,837.707092,1.679591,105138.0,99.645973,NaN,0,147653.0,2110.0,2063.0
28,1,300.668732,20.274799,895.609863,1.907034,105230.0,87.046127,NaN,0,147803.0,2105.0,2558.0

In [13]:
gpu_tracking.characterize_points(
    r'/Users/amfaber/Documents/tracking_script/gpu-tracking/testing/easy_test_data.tif',
    df,
    9,
    filter_close = True,
    characterize = True,
    doughnut_correction = True,
    snr = 0,
    minmass_snr = 0.3,
    truncate_preprocessed = True,
)

,frame,y,x,mass,Rg,raw,signal,ecc,raw_mass,raw_bg_median,raw_mass_corrected
0,0,413.065247,502.980103,1346.004639,1.635221,105696.0,148.588654,NaN,147771.0,2088.0,3699.0
1,0,111.672752,333.889984,2523.538574,1.676097,108940.0,258.473419,NaN,151559.0,2113.0,5762.0
2,0,454.033142,360.019714,800.005371,1.806427,104637.0,85.453979,NaN,147079.0,2105.0,1834.0
3,0,390.241364,220.055573,890.364929,1.791560,104342.0,86.039795,NaN,146567.0,2095.0,2012.0
4,0,219.481674,280.281616,1579.095215,1.964314,107415.0,138.752411,NaN,149939.0,2106.0,4625.0
...,...,...,...,...,...,...,...,...,...,...,...
251455,4999,182.327896,372.077423,2685.176025,1.712738,110298.0,233.810562,NaN,152922.0,2112.0,7194.0
251456,4999,81.985001,400.797729,1206.162354,2.199495,106472.0,75.241310,NaN,148833.0,2106.0,3519.0
251457,4999,114.145241,235.099091,938.776062,2.021075,104882.0,80.681259,NaN,146865.0,2102.0,1827.0
251458,4999,212.951523,217.151917,939.191040,1.536493,105319.0,120.455551,NaN,147868.0,2107.0,2485.0
251459,4999,19.599836,259.049072,1050.218262,1.751278,105143.0,112.735466,NaN,147083.0,2090.0,2873.0