In [1]:
import gpu_tracking as gt
df = gt.LoG(
    # r'../easy_test_data.tif',
    r'C:\Users\andre\Documents\tracking_optimizations\gpu-tracking\tiff_vsi\vsi dummy\Process_9747.vsi',
    2.3, 3.5,
    # characterize = True,
    # doughnut_correction = True,
    snr = 1.5,
    minmass_snr = 0.3,
    truncate_preprocessed = True,
    # search_range = 15
)

100%|██████████| 2000/2000 [00:08<00:00, 231.25it/s]

In [3]:
from tqdm import tqdm

In [6]:
with tqdm() as pbar:
    for i in range(5):
        pbar.total = None
        pbar.n = i
        pbar.refresh()

4it [00:00, 798.76it/s]

In [4]:
df

,frame,y,x,mass,Rg,raw,signal,ecc,raw_mass,raw_bg_median,raw_mass_corrected
0,0,476.277313,50.944580,0.441052,1.502595,49.767818,0.050549,0.032055,147117.0,2107.0,1734.0
1,0,300.862000,19.940107,0.377028,1.615872,49.750294,0.047149,0.077920,147653.0,2110.0,2063.0
2,0,242.058044,45.830429,0.469764,1.542741,49.830009,0.058932,0.213972,148073.0,2108.0,2621.0
3,0,331.988007,47.484997,0.541241,2.025119,50.188942,0.050498,0.364750,148203.0,2105.0,2958.0
4,0,167.238831,101.559586,0.613339,1.832968,50.309013,0.055553,0.321101,149366.0,2107.0,3983.0
...,...,...,...,...,...,...,...,...,...,...,...
197433,4999,353.678589,252.230377,1.365863,1.624923,51.744621,0.141750,0.073209,152283.0,2116.0,6279.0
197434,4999,248.304062,215.483414,0.899327,2.063851,50.759636,0.066531,0.431606,151103.0,2112.0,5375.0
197435,4999,216.831482,314.092438,0.905342,1.816406,51.063477,0.070816,0.204953,151585.0,2114.0,5719.0
197436,4999,394.833282,259.949860,1.301139,2.094694,51.990067,0.102580,0.350303,154939.0,2110.0,9349.0
197437,4999,190.319244,292.127075,0.912979,1.988507,51.404430,0.069455,0.138942,152471.0,2116.0,6467.0

In [13]:
gpu_tracking.characterize_points(
    r'/Users/amfaber/Documents/tracking_script/gpu-tracking/testing/easy_test_data.tif',
    df,
    9,
    filter_close = True,
    characterize = True,
    doughnut_correction = True,
    snr = 0,
    minmass_snr = 0.3,
    truncate_preprocessed = True,
)

,frame,y,x,mass,Rg,raw,signal,ecc,raw_mass,raw_bg_median,raw_mass_corrected
0,0,413.065247,502.980103,1346.004639,1.635221,105696.0,148.588654,NaN,147771.0,2088.0,3699.0
1,0,111.672752,333.889984,2523.538574,1.676097,108940.0,258.473419,NaN,151559.0,2113.0,5762.0
2,0,454.033142,360.019714,800.005371,1.806427,104637.0,85.453979,NaN,147079.0,2105.0,1834.0
3,0,390.241364,220.055573,890.364929,1.791560,104342.0,86.039795,NaN,146567.0,2095.0,2012.0
4,0,219.481674,280.281616,1579.095215,1.964314,107415.0,138.752411,NaN,149939.0,2106.0,4625.0
...,...,...,...,...,...,...,...,...,...,...,...
251455,4999,182.327896,372.077423,2685.176025,1.712738,110298.0,233.810562,NaN,152922.0,2112.0,7194.0
251456,4999,81.985001,400.797729,1206.162354,2.199495,106472.0,75.241310,NaN,148833.0,2106.0,3519.0
251457,4999,114.145241,235.099091,938.776062,2.021075,104882.0,80.681259,NaN,146865.0,2102.0,1827.0
251458,4999,212.951523,217.151917,939.191040,1.536493,105319.0,120.455551,NaN,147868.0,2107.0,2485.0
251459,4999,19.599836,259.049072,1050.218262,1.751278,105143.0,112.735466,NaN,147083.0,2090.0,2873.0